name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GOOGLE_PLACE_API_KEY: ${{ secrets.GG_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: "Lint"
        run: npm run lint
      - name: "Test"
        run: npm run test
      - name: "Audit"
        run: npm run audit

      - name: Wait For Other Pipelines
        uses: otto-de/github-actions-wait@v1.0
        with:
          step-name: "Audit"
      - name: "test"
        run: npm run audit
      - name: "test"
        run: npm run audit
